In [ ]:
import nltk
import spacy
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords

# Download necessary NLTK resources
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
text = "The striped bats are hanging on their feet for best comfort."
tokens = word_tokenize(text)
print(f"Original Text: {text}")

Original Text: The striped bats are hanging on their feet for best comfort.


In [ ]:
# a) NLTK: Stemming
stemmer = PorterStemmer()
nltk_stemmed = [stemmer.stem(token) for token in tokens]
print(f"NLTK Stemmed: {nltk_stemmed}")

NLTK Stemmed: ['the', 'stripe', 'bat', 'are', 'hang', 'on', 'their', 'feet', 'for', 'best', 'comfort', '.']


In [ ]:
# b) NLTK: Lemmatization and Stopword Removal
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
nltk_lemmatized = [
    lemmatizer.lemmatize(w.lower())
    for w in tokens
    if w.lower() not in stop_words and w.isalpha()
]
print(f"NLTK Lemmatized: {nltk_lemmatized}")

NLTK Lemmatized: ['striped', 'bat', 'hanging', 'foot', 'best', 'comfort']


In [ ]:
# c) Spacy: Lemmatization and Stopword Removal
try:
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    spacy_processed = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]
except OSError:
    spacy_processed = "Error: spacy model 'en_core_web_sm' not found. Run !python -m spacy download en_core_web_sm"

print(f"Spacy Processed: {spacy_processed}")

Spacy Processed: ['striped', 'bat', 'hang', 'foot', 'good', 'comfort']


In [2]:
# ==============================
# DISPLAY WEIGHTS AND BIASES
# ==============================

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# For TensorFlow / Keras Models
print("===== MODEL WEIGHTS & BIASES =====\n")

# --- FIX START ---
# Define a simple dummy model for demonstration to resolve NameError.
# In a real scenario, 'model' would be your actual trained or loaded model.
model = keras.Sequential([
    layers.Input(shape=(10,)), # Input layer needs a shape
    layers.Dense(5, activation='relu', name='first_dense'),
    layers.Dense(1, activation='sigmoid', name='output_dense')
])
# --- FIX END ---

for i, layer in enumerate(model.layers):

    params = layer.get_weights()

    if len(params) > 0:
        print(f"\nLayer {i+1}: {layer.name}")

        # Weights
        weights = params[0]
        print("\nWeights:")
        print(weights)

        # Biases
        if len(params) > 1:
            biases = params[1]
            print("\nBiases:")
            print(biases)

        print("-" * 50)

===== MODEL WEIGHTS & BIASES =====


Layer 1: first_dense

Weights:
[[-0.22384512  0.3601216   0.09177935 -0.02799278  0.15217113]
 [-0.43851128  0.60057753  0.25470144 -0.18269402  0.0773651 ]
 [ 0.24375159  0.5311946   0.02422369  0.49615616 -0.11986846]
 [-0.06864452  0.20239055 -0.0361262   0.12261719 -0.34579104]
 [ 0.41345793  0.49846643  0.53521377 -0.605877    0.42931002]
 [-0.30724978  0.18851674 -0.43841445 -0.3899569   0.5363161 ]
 [-0.12367135 -0.44954136  0.10859275  0.5478576  -0.27200463]
 [ 0.12217283  0.3705004   0.15379906  0.5036691  -0.35553685]
 [ 0.06646878  0.43640488  0.39075774 -0.5565355  -0.32296172]
 [-0.40577662  0.5552791   0.31037742 -0.3409053   0.18098873]]

Biases:
[0. 0. 0. 0. 0.]
--------------------------------------------------

Layer 2: output_dense

Weights:
[[-0.30916595]
 [-0.16764212]
 [-0.79742336]
 [-0.33123088]
 [-0.38618827]]

Biases:
[0.]
--------------------------------------------------
